name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: "yarn"

    - id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - run: yarn install --frozen-lockfile
      shell: bash
