name: Build API Doc
description: Build API Doc

runs:
  using: "composite"
  steps:
    - run: |
        uv run --no-sync python scripts/build_api_docs.py
        cp -r ./build/nonebot/adapters/feishu/* ./website/docs/api/
        yarn prettier
      shell: bash
