name: Ruff Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "nonebot/**"
      - "packages/**"
      - "tests/**"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ruff-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
